version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ${STORAGE_FOLDER}:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  redis:
    image: redis:latest

  server:
    build:
      dockerfile: Dockerfile
    command: python server.py
    environment:
      WORKER_BROKER_URL: ${WORKER_BROKER_URL}
      WORKER_BACKEND_URL: ${WORKER_BACKEND_URL}
      WORKER_APP_NAME: ${WORKER_APP_NAME}
      WORKER_TASK_NAME: ${WORKER_TASK_NAME}
      WORKER_CALLBACK_URL: ${WORKER_CALLBACK_URL}
      STORAGE_FOLDER: ${STORAGE_FOLDER}
      STORAGE_BASE_URL:  ${STORAGE_BASE_URL}
    volumes:
      - ./:/app
    depends_on:
      - redis


  worker:
    image: ghcr.io/yushiang-demo/dula-net-worker:latest
    command: celery -A worker worker --loglevel=info
    environment:
      WORKER_BROKER_URL: ${WORKER_BROKER_URL}
      WORKER_BACKEND_URL: ${WORKER_BACKEND_URL}
      WORKER_APP_NAME: ${WORKER_APP_NAME}
      WORKER_TASK_NAME: ${WORKER_TASK_NAME}
    depends_on:
      - redis

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_SITE_BASEURL: /mongoadmin
    depends_on:
      - mongo